//go:build !ignore_autogenerated

/*
Copyright 2026 Signal24.

Licensed under the MIT License.
See LICENSE file in the project root for full license text.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionResult) DeepCopyInto(out *ActionResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionResult.
func (in *ActionResult) DeepCopy() *ActionResult {
	if in == nil {
		return nil
	}
	out := new(ActionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTarget) DeepCopyInto(out *ClusterTarget) {
	*out = *in
	if in.OnFailover != nil {
		in, out := &in.OnFailover, &out.OnFailover
		*out = new(TransitionActions)
		(*in).DeepCopyInto(*out)
	}
	if in.OnFailback != nil {
		in, out := &in.OnFailback, &out.OnFailback
		*out = new(TransitionActions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTarget.
func (in *ClusterTarget) DeepCopy() *ClusterTarget {
	if in == nil {
		return nil
	}
	out := new(ClusterTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionKillStatus) DeepCopyInto(out *ConnectionKillStatus) {
	*out = *in
	if in.ExpectedNodes != nil {
		in, out := &in.ExpectedNodes, &out.ExpectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AckedNodes != nil {
		in, out := &in.AckedNodes, &out.AckedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SignaledAt != nil {
		in, out := &in.SignaledAt, &out.SignaledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionKillStatus.
func (in *ConnectionKillStatus) DeepCopy() *ConnectionKillStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionKillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverAction) DeepCopyInto(out *FailoverAction) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(JobAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(ScaleAction)
		(*in).DeepCopyInto(*out)
	}
	if in.WaitReady != nil {
		in, out := &in.WaitReady, &out.WaitReady
		*out = new(WaitReadyAction)
		(*in).DeepCopyInto(*out)
	}
	if in.WaitRemote != nil {
		in, out := &in.WaitRemote, &out.WaitRemote
		*out = new(WaitRemoteAction)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.RetryIntervalSeconds != nil {
		in, out := &in.RetryIntervalSeconds, &out.RetryIntervalSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverAction.
func (in *FailoverAction) DeepCopy() *FailoverAction {
	if in == nil {
		return nil
	}
	out := new(FailoverAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverEvent) DeepCopyInto(out *FailoverEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverEvent.
func (in *FailoverEvent) DeepCopy() *FailoverEvent {
	if in == nil {
		return nil
	}
	out := new(FailoverEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailoverEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverEventList) DeepCopyInto(out *FailoverEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FailoverEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverEventList.
func (in *FailoverEventList) DeepCopy() *FailoverEventList {
	if in == nil {
		return nil
	}
	out := new(FailoverEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailoverEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverEventSpec) DeepCopyInto(out *FailoverEventSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverEventSpec.
func (in *FailoverEventSpec) DeepCopy() *FailoverEventSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverEventStatus) DeepCopyInto(out *FailoverEventStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.PreActionResults != nil {
		in, out := &in.PreActionResults, &out.PreActionResults
		*out = make([]ActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostActionResults != nil {
		in, out := &in.PostActionResults, &out.PostActionResults
		*out = make([]ActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectionKillResult != nil {
		in, out := &in.ConnectionKillResult, &out.ConnectionKillResult
		*out = new(ConnectionKillStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverEventStatus.
func (in *FailoverEventStatus) DeepCopy() *FailoverEventStatus {
	if in == nil {
		return nil
	}
	out := new(FailoverEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverService) DeepCopyInto(out *FailoverService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverService.
func (in *FailoverService) DeepCopy() *FailoverService {
	if in == nil {
		return nil
	}
	out := new(FailoverService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailoverService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverServiceList) DeepCopyInto(out *FailoverServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FailoverService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverServiceList.
func (in *FailoverServiceList) DeepCopy() *FailoverServiceList {
	if in == nil {
		return nil
	}
	out := new(FailoverServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailoverServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverServiceSpec) DeepCopyInto(out *FailoverServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	in.PrimaryCluster.DeepCopyInto(&out.PrimaryCluster)
	in.FailoverCluster.DeepCopyInto(&out.FailoverCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverServiceSpec.
func (in *FailoverServiceSpec) DeepCopy() *FailoverServiceSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverServiceStatus) DeepCopyInto(out *FailoverServiceStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.LastKnownFailoverActive != nil {
		in, out := &in.LastKnownFailoverActive, &out.LastKnownFailoverActive
		*out = new(bool)
		**out = **in
	}
	if in.SpecChangeTime != nil {
		in, out := &in.SpecChangeTime, &out.SpecChangeTime
		*out = (*in).DeepCopy()
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteState != nil {
		in, out := &in.RemoteState, &out.RemoteState
		*out = new(RemoteState)
		(*in).DeepCopyInto(*out)
	}
	if in.Transition != nil {
		in, out := &in.Transition, &out.Transition
		*out = new(TransitionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverServiceStatus.
func (in *FailoverServiceStatus) DeepCopy() *FailoverServiceStatus {
	if in == nil {
		return nil
	}
	out := new(FailoverServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAction) DeepCopyInto(out *HTTPAction) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAction.
func (in *HTTPAction) DeepCopy() *HTTPAction {
	if in == nil {
		return nil
	}
	out := new(HTTPAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobAction) DeepCopyInto(out *JobAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobAction.
func (in *JobAction) DeepCopy() *JobAction {
	if in == nil {
		return nil
	}
	out := new(JobAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteState) DeepCopyInto(out *RemoteState) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.SpecChangeTime != nil {
		in, out := &in.SpecChangeTime, &out.SpecChangeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteState.
func (in *RemoteState) DeepCopy() *RemoteState {
	if in == nil {
		return nil
	}
	out := new(RemoteState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleAction) DeepCopyInto(out *ScaleAction) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleAction.
func (in *ScaleAction) DeepCopy() *ScaleAction {
	if in == nil {
		return nil
	}
	out := new(ScaleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionActions) DeepCopyInto(out *TransitionActions) {
	*out = *in
	if in.PreActions != nil {
		in, out := &in.PreActions, &out.PreActions
		*out = make([]FailoverAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostActions != nil {
		in, out := &in.PostActions, &out.PostActions
		*out = make([]FailoverAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionActions.
func (in *TransitionActions) DeepCopy() *TransitionActions {
	if in == nil {
		return nil
	}
	out := new(TransitionActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionStatus) DeepCopyInto(out *TransitionStatus) {
	*out = *in
	if in.PreActionResults != nil {
		in, out := &in.PreActionResults, &out.PreActionResults
		*out = make([]ActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostActionResults != nil {
		in, out := &in.PostActionResults, &out.PostActionResults
		*out = make([]ActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ConnectionKill != nil {
		in, out := &in.ConnectionKill, &out.ConnectionKill
		*out = new(ConnectionKillStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionStatus.
func (in *TransitionStatus) DeepCopy() *TransitionStatus {
	if in == nil {
		return nil
	}
	out := new(TransitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitReadyAction) DeepCopyInto(out *WaitReadyAction) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitReadyAction.
func (in *WaitReadyAction) DeepCopy() *WaitReadyAction {
	if in == nil {
		return nil
	}
	out := new(WaitReadyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitRemoteAction) DeepCopyInto(out *WaitRemoteAction) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(FailoverPhase)
		**out = **in
	}
	if in.ActionName != nil {
		in, out := &in.ActionName, &out.ActionName
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeoutSeconds != nil {
		in, out := &in.ConnectTimeoutSeconds, &out.ConnectTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ActionTimeoutSeconds != nil {
		in, out := &in.ActionTimeoutSeconds, &out.ActionTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitRemoteAction.
func (in *WaitRemoteAction) DeepCopy() *WaitRemoteAction {
	if in == nil {
		return nil
	}
	out := new(WaitRemoteAction)
	in.DeepCopyInto(out)
	return out
}
