{{- if .Values.connectionKiller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-failover-manager.connectionKillerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-failover-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: connection-killer
{{- end }}
