{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-failover-manager.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-failover-manager.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - name: https
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "k8s-failover-manager.selectorLabels" . | nindent 4 }}
{{- end }}
